### PR TITLE
Lazy load objects initialization

### PR DESCRIPTION
**Pull request by H4ad**
Continuation of #43

Instead of caching at build time, I just lazy load the initialization of the objects:

Before:

```bash
$ hyperfine --warmup 3 "node ./index.js" 
Benchmark 1: node ./index.js
  Time (mean ± σ):     109.1 ms ±   1.8 ms    [User: 96.6 ms, System: 36.7 ms]
  Range (min … max):   102.8 ms … 112.9 ms    27 runs

```

After:

```bash
$ hyperfine --warmup 3 "node ./index.js"
Benchmark 1: node ./index.js
  Time (mean ± σ):     105.2 ms ±   1.1 ms    [User: 93.4 ms, System: 34.8 ms]
  Range (min … max):   103.4 ms … 108.7 ms    27 runs

```

### CODE REVIEW

**Comment by kemitchell** [comment]
Thanks!

One last thing before I put this on my to-do list: Do you license your work here under [Apache 2.0](https://apache.org/licenses/LICENSE-2.0)?

**Comment by H4ad** [comment]
> Do you license your work here under [Apache 2.0](https://apache.org/licenses/LICENSE-2.0)?

Yes, no problem.

**Comment by kemitchell** [comment]
Thanks so much. This is on my list and top of my inbox.

**Comment by kemitchell** [comment]
Do I correctly understand that the benefit here, at least on the version of Node tested, is on the order of many a single millisecond during initial load? That in exchange for calling a function to load each variable?

I think it's safe to assume that where this module gets loaded, it will also be invoked. If it's not being invoked, the perf fix would be to not load in the first place.

**Comment by kemitchell** [comment]
Would you expect a similar 4ms delay on first invocation?

**Comment by H4ad** [comment]
> Would you expect a similar 4ms delay on first invocation?

What do you mean?

**Comment by kemitchell** [comment]
Will the first call to the function the package exports take an additional 4ms to initialize all the variables now returned from the loader helper functions?

**Comment by H4ad** [comment]
> Will the first call to the function the package exports take an additional 4ms to initialize all the variables now returned from the loader helper functions?

Yes.

The overall time will be the same, we save 4ms during load time but we spent 4ms in the first call for the package.

**Comment by kemitchell** [comment]
I don't mean to see overly resistant here. I appreciate you taking the time to answer my questions!

If the trade-off is just _when_ initial loading occurs, I wonder why it's better for the package to prescribe data loading on invocation over preemptive data loading on module load. Particularly since `require` and dynamic `import()` allow users to defer package loading without any changes to the implementation of the package, but there's no existing mechanism for making a package coded to load on invocation to load preemptively, instead.

This package is in many ways a bunch of plain-text lists and mappings, pieced together with relatively thin layers of glue code. So not the worst place to look for a load-related perf win or load-time/runtime arbitrage. And `npm run` may indeed have been suffering, with me still wondering why it loads this package at all. But I'm not sure fairly rote wrappings of global vars in getter functions really makes sense.

**Comment by H4ad** [comment]
> Particularly since require and dynamic import() allow users to defer package loading without any changes to the implementation of the package

Yes, but people usually don't know how much time each dependency takes to load, I'm working on Node to add a feature to let them know the amount of time that takes to load but people usually think is zero-cost or something really fast (1~3ms).

> And npm run may indeed have been suffering, with me still wondering why it loads this package at all.

I removed this package from the hot-path, now this package is only loaded when NPM needs to validate licenses (when run npm init, for example).

If you think that is not worth introducing this change, that's ok for me since my main issue was to reduce load time of `npm run` only.

**Comment by kemitchell** [comment]
@H4ad I just added a performance note about load time and dynamic `import()` to README:

0bf80b1c488d42759ead43a23b16741b782433b6

If hope you don't mind that I thanked you by name! Thanks again for your issue and PR here.

**Comment by H4ad** [comment]
That's okay, thanks for your time!

**Pull request closed without merging**
