### PR TITLE
Adds travis jobs on ppc64le

### PR DESCRIPTION
**Pull request by dineshks1**
This PR adds power support on travis.

### CODE REVIEW

**Comment by kemitchell** [comment]
Did you see an arch-specific failure on Power?

**Comment by dineshks1** [comment]
The build is successful for ppc64le and amd64 arch without any failure.

**Comment by kemitchell** [comment]
Why test both? AFAIK this is a pure-JS Node module.

**Comment by kemitchell** [comment]
I've just pushed a5485472386236d352add8c2609723f657ce5d93, which replaces Travis CI, whose terms and availability are changing, with a GitHub Action.

It's not great trouble on my part to test on multiple architectures. But I don't think this package is doing anything arch-dependent. If there's an arch-specific problem with this package, it's like a problem inherited from Node itself.

**Comment by dineshks1** [comment]
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing,For more info tag @gerrith3.

**Comment by dineshks1** [comment]
Please review this merge.

**Comment by kemitchell** [comment]
@gerrith3, @dineshks1, if you want to include this npm package in your distribution, say as part of the npm CLI, be my guest. But please handle CI, QC, or other processes specific to your needs on your own.

Fundamentally, this is a tiny npm module in pure JavaScript. The only Node API it uses is the module system. There's nothing platform-specific about it.

**Pull request closed without merging**
