### PR TITLE
Fix BSD 3 clause license

### PR DESCRIPTION
**Pull request by zommerfelds**
This has a relatively small effect (I found 55 wrongly corrected packages), but would be nice to fix anyway.

### CODE REVIEW

**Comment by kemitchell** [comment]
Hmm. Wikipedia and other sources use these descriptions, but I'm not sure their meanings are that reliable in the community.

**Comment by zommerfelds** [comment]
Haha, yep that's where I got it from. :) But also here:
https://opensource.org/licenses/BSD-3-Clause
> Note: This license has also been called the "New BSD License" or "Modified BSD License"

Seems pretty official.

**Comment by kemitchell** [comment]
There is confusion.

From OSI:
- BSD-3-Clause AKA "New BSD License", "Modified BSD License"
- BSD-2-Clause AKA "Simplified BSD License", "FreeBSD License"

From SPDX:
- BSD 3-Clause (BSD 3-clause "New" or "Revised" License)
- BSD-2-Clause (BSD 2-clause "Simplified" License)
- BSD-2-Clause-FreeBSD (BSD 2-clause FreeBSD License)
- BSD-2-Clause-NetBSD (BSD 2-clause NetBSD License)

**Comment by kemitchell** [comment]
Unfortunately, "new", "revised", and "modified" describe literally all the BSD variants, except perhaps BSD-4-Clause. Which one they refer to depends on your time frame of reference.

For instance, there are now "newer" and more recently "revised" and "modified" variants, like 0BSD and forthcoming BSD+Patents/BSD-plus-Patents.

It's a mess.

**Comment by zommerfelds** [comment]
Hmm, yeah seems messy. However, not sure what the general philosophy here is. Wouldn't be guessing BSD-2-Clause for any of those three words more wrong than guessing BSD-3-Clause?

**Comment by kemitchell** [comment]
@zommerfelds: "What's the scope of this" is always a good question.

Unfortunately, to my mind, this package doesn't really have a nice, neat, clearly defined purpose. It's not "pure" and technical like `spdx-expression-parse`, but more functional.

Here's how I see it.

Basically, folks put all kinds of stuff in `package.json`'s `license` property, or wherever SPDX is expected.  It's _correct_ to give them a validation error and point them to SPDX by way of, say, the `package.json` spec.  But that's also kind of throwing them into deep water---_two_ specs, one of which is spread across webpages and a many-page PDF. That's particularly rough treatment if what they wrote was clear to a knowledgeable reader, but just didn't happen to be the string that SPDX chose. `Apache 2.0`, for example.

The insight that gave rise to the package was based on census of npm registry data. Basically, there remains enormous "noise" in what folks type into `package.json`, but many invalid strings are unambiguous in meaning, and you can correct ~90+% of them with just a few simple, mechanical transformations, applied guess-and-check style.

I'm not sure that chasing the remaining ~10% of cases is worthwhile, especially if it involves speculating about the psychology---or license politics---of users who, by definition, don't grok SPDX or, say, the fact that their preferred string is ambiguous among many standardized license forms.  Especially if it involves making decisions about privileging one interpretation of imprecise `license` values over another, which is a very easy way to invite interminable, mostly political, feedback.  Not great a great drama-benefit analysis in that direct, I think.

If you're of a mind to dive in and go for closer to 100% "community coverage", please don't let me stop you.  As long as the implementation remains relatively simple, reasonably performant, and not gratingly "biased" in favor of any particular terms, I don't see why `npm init` and friends shouldn't use it.

Part of the point of moving all my meaningful license-related packages to the jslicense org was to give _other_ folks more recognition and "ownership" of those pieces of the puzzle.

**Comment by zommerfelds** [comment]
Hi @kemitchell, yeah that all makes sense. Thanks for the comment.

> The insight that gave rise to the package was based on census of npm registry data. Basically, there remains enormous "noise" in what folks type into package.json, but many invalid strings are unambiguous in meaning, and you can correct ~90+% of them with just a few simple, mechanical transformations, applied guess-and-check style.

So I'm assuming you did a similar methodology than me for finding those transformations. That's cool. :) You are right this PR makes very little difference. For some reason I got motivation to analyze npm data and see what kind of mistakes there are to be corrected. I don't plan to make more of this kind of change.

How helpful this change is I don't know, but I didn't see much harm in adding those couples of lines that to me seemed like making the most reasonable correction given quick Google searches :) I'll close it for now for the reason of "not knowing what would be appropriate to suggest as a correction".

**Pull request closed without merging**
