### PR TITLE
Add support for more common spellings of BSD license variants

### PR DESCRIPTION
**Pull request by taleinat**
Examples:
* NetBSD
* FreeBSD
* Modified BSD License
* New BSD License
* Revised BSD License
* Simplified BSD License
* Clear BSD License
* Old / Original BSD License

For details, see:
 * https://en.wikipedia.org/wiki/BSD_licenses
 * https://spdx.org/licenses/

### CODE REVIEW

**Comment by kemitchell** [comment]
@taleinat, thanks!

Do you license these contributions under the Apache License 2.0?

If you're employed or working for a client, do have their written permission to license under Apache 2.0?

**Comment by taleinat** [comment]
> Do you license these contributions under the Apache License 2.0?

Yes, I'm happy to license this under that license.

> If you're employed or working for a client, do have their written permission to license under Apache 2.0?

This is related to work I'm doing for a client, and I have written permission from them to contribute such changes to open-source projects with permissive licenses such as Apache-2.0. I can supply written permission for this specific set of changes if needed.

**Comment by kemitchell** [comment]
Thanks, @taleinat. We're all good.

**Comment by kemitchell** [comment]
v3.1.1

**Pull request merged**
