### PR TITLE
Fix incorrect transpositions for LGPL and other inputs containing "GPL" or "General Public License"

### PR DESCRIPTION
**Pull request by lkoskela**
This PR fixes a number of incorrect transpositions related to "GPL" or "General Public License".

Firstly, it corrects a mistake in the existing transpositions where LGPL patterns are explicitly mapped to GPL, not LGPL:

```diff
-  'GNU LESSER GENERAL PUBLIC LICENSE': 'GPL-3.0-or-later',
+  'GNU LESSER GENERAL PUBLIC LICENSE': 'LGPL',

-  'GNU LGPL v3.0': 'GPL-3.0-or-later',
+  'GNU LGPL v3.0': 'LGPL-3.0-or-later',
```

Second, it adds additional transpositions to try and match specific version numbers of GPL/LGPL.

Finally, and perhaps most importantly, this PR applies a sort to the transpositions such that we'll try replacing longer substrings before shorter substrings. This is to avoid a common substring such as "GENERAL PUBLIC LICENSE" from matching to "LESSER GENERAL PUBLIC LICENSE" before a more accurate match simply because of the order they were defined in the array.

### CODE REVIEW

**Comment by kemitchell** [comment]
This looks like good work!

Turns out I didn't have our CI GitHub Action set to run on pull requests, so it wasn't triggered here. I've fixed that on `master`. Tests pass here on manual run.

@lkoskela can you confirm your work here is licensed under Apache 2.0?

**Comment by lkoskela** [comment]
> @lkoskela can you confirm your work here is licensed under Apache 2.0?

Confirmed 👍

**Comment by kemitchell** [comment]
@lkoskela, thanks for confirming.

Any thoughts on major or minor version bump?

**Comment by lkoskela** [comment]
> Any thoughts on major or minor version bump?

I’d vote for minor. I can imagine an end user for whom this might seem like a ”breaking” change if their inputs suddenly come out as a different license than before but I would argue that conceptually nothing changes – we’re simply improving accuracy.

**Comment by kemitchell** [comment]
Published spdx-correct@3.2.0

**Pull request merged**
